name: ItemGeneratorX
author: Shin1gamiX
description: A custom plugin for WhiteWolf.
version: 0.1
main: net.shin1gamix.generators.Core
depend: [HolographicDisplays]
commands:
  itemgeneratorx:
    description: The basic command.
    aliases: [generator, gen, generatorx, genx, itemgenerator]